// Dados de catálogo (peças e acessórios) para o seed.
// `categoriaRef` = slug da categoria. `compat` = slugs de ModeloVeiculo.

const categorias = [
  { slug: 'motor', nome: 'Motor', tipo: 'PECA' },
  { slug: 'freios', nome: 'Freios', tipo: 'PECA' },
  { slug: 'suspensao', nome: 'Suspensão', tipo: 'PECA' },
  { slug: 'eletrica', nome: 'Elétrica', tipo: 'PECA' },
  { slug: 'filtros', nome: 'Filtros', tipo: 'PECA' },
  { slug: 'som-multimidia', nome: 'Som e Multimídia', tipo: 'ACESSORIO' },
  { slug: 'estetica', nome: 'Estética', tipo: 'ACESSORIO' },
  { slug: 'conforto', nome: 'Conforto', tipo: 'ACESSORIO' },
  { slug: 'rodas-pneus', nome: 'Rodas e Pneus', tipo: 'ACESSORIO' },
];

const pecas = [
  {
    slug: 'pastilha-freio-dianteira',
    nome: 'Pastilha de Freio Dianteira',
    descricao: 'Jogo de pastilhas dianteiras com composto cerâmico, baixo ruído e menor geração de pó.',
    preco: 189.9,
    estoque: 24,
    sku: 'FR-PD-001',
    categoriaRef: 'freios',
    compat: ['chevrolet-celta', 'fiat-palio', 'volkswagen-gol'],
  },
  {
    slug: 'disco-freio-ventilado',
    nome: 'Disco de Freio Ventilado (par)',
    descricao: 'Par de discos ventilados dianteiros, ferro fundido de alto carbono.',
    preco: 419.0,
    estoque: 8,
    sku: 'FR-DV-002',
    categoriaRef: 'freios',
    compat: ['toyota-corolla'],
  },
  {
    slug: 'kit-embreagem',
    nome: 'Kit de Embreagem',
    descricao: 'Kit completo: platô, disco e rolamento. Acionamento suave e durabilidade reforçada.',
    preco: 689.9,
    estoque: 6,
    sku: 'MT-EMB-010',
    categoriaRef: 'motor',
    compat: ['volkswagen-gol', 'fiat-palio'],
  },
  {
    slug: 'correia-dentada',
    nome: 'Correia Dentada com Tensor',
    descricao: 'Correia dentada e tensor automático. Substituição recomendada a cada 50.000 km.',
    preco: 274.5,
    estoque: 15,
    sku: 'MT-CD-011',
    categoriaRef: 'motor',
    compat: ['fiat-palio', 'chevrolet-celta'],
  },
  {
    slug: 'jogo-velas-ignicao',
    nome: 'Jogo de Velas de Ignição',
    descricao: 'Quatro velas com eletrodo de níquel-ítrio. Melhora a partida a frio e o consumo.',
    preco: 129.9,
    estoque: 40,
    sku: 'MT-VI-012',
    categoriaRef: 'motor',
    compat: ['toyota-corolla', 'volkswagen-gol', 'chevrolet-celta'],
  },
  {
    slug: 'jogo-juntas-motor',
    nome: 'Jogo de Juntas do Motor',
    descricao: 'Conjunto completo de juntas para retífica. Inclui junta do cabeçote multicamadas.',
    preco: 349.0,
    estoque: 4,
    sku: 'MT-JJ-013',
    categoriaRef: 'motor',
    compat: ['volkswagen-fusca', 'chevrolet-opala'],
  },
  {
    slug: 'amortecedor-dianteiro',
    nome: 'Amortecedor Dianteiro (par)',
    descricao: 'Par de amortecedores pressurizados a gás. Estabilidade e conforto em piso irregular.',
    preco: 528.0,
    estoque: 10,
    sku: 'SU-AD-020',
    categoriaRef: 'suspensao',
    compat: ['chevrolet-celta', 'volkswagen-gol'],
  },
  {
    slug: 'bateria-60ah',
    nome: 'Bateria 60Ah',
    descricao: 'Bateria selada livre de manutenção, 18 meses de garantia.',
    preco: 459.9,
    estoque: 20,
    sku: 'EL-BT-030',
    categoriaRef: 'eletrica',
    compat: ['chevrolet-celta', 'fiat-palio', 'volkswagen-gol', 'toyota-corolla'],
  },
  {
    slug: 'bomba-combustivel',
    nome: 'Bomba de Combustível',
    descricao: 'Bomba elétrica de baixa pressão para veículos carburados com conversão.',
    preco: 312.0,
    estoque: 5,
    sku: 'EL-BC-031',
    categoriaRef: 'eletrica',
    compat: ['chevrolet-opala', 'volkswagen-fusca'],
  },
  {
    slug: 'filtro-oleo',
    nome: 'Filtro de Óleo',
    descricao: 'Elemento filtrante de alta eficiência com válvula anti-retorno.',
    preco: 34.9,
    estoque: 80,
    sku: 'FI-FO-040',
    categoriaRef: 'filtros',
    compat: ['chevrolet-celta', 'fiat-palio', 'volkswagen-gol', 'toyota-corolla'],
  },
  {
    slug: 'filtro-ar-esportivo',
    nome: 'Filtro de Ar Esportivo',
    descricao: 'Filtro lavável de fluxo livre. Reutilizável por até 80.000 km.',
    preco: 159.0,
    estoque: 0,
    sku: 'FI-FA-041',
    categoriaRef: 'filtros',
    compat: ['volkswagen-gol', 'chevrolet-celta'],
  },
];

const acessorios = [
  {
    slug: 'central-multimidia-9',
    nome: 'Central Multimídia 9" Android',
    descricao: 'Tela sensível ao toque, espelhamento sem fio, GPS e câmera de ré inclusa.',
    preco: 1290.0,
    estoque: 12,
    sku: 'AC-MM-100',
    categoriaRef: 'som-multimidia',
    compat: ['chevrolet-celta', 'volkswagen-gol', 'fiat-palio'],
  },
  {
    slug: 'suporte-veicular-celular',
    nome: 'Suporte Veicular para Celular',
    descricao: 'Fixação magnética no painel, rotação 360°.',
    preco: 49.9,
    estoque: 60,
    sku: 'AC-SV-101',
    categoriaRef: 'som-multimidia',
    compat: [],
  },
  {
    slug: 'pelicula-insulfilm',
    nome: 'Kit Película Insulfilm G20',
    descricao: 'Película para todos os vidros, proteção UV e conforto térmico. Instalação inclusa.',
    preco: 320.0,
    estoque: 18,
    sku: 'AC-PI-110',
    categoriaRef: 'estetica',
    compat: [],
  },
  {
    slug: 'kit-farol-led',
    nome: 'Kit Farol de LED',
    descricao: 'Lâmpadas LED 6000K, alcance 30% maior que halógena. Par com driver embutido.',
    preco: 289.9,
    estoque: 22,
    sku: 'AC-FL-111',
    categoriaRef: 'estetica',
    compat: ['chevrolet-celta', 'volkswagen-gol'],
  },
  {
    slug: 'jogo-tapetes-borracha',
    nome: 'Jogo de Tapetes de Borracha',
    descricao: 'Tapetes moldados com bordas altas. Não deslizam e são laváveis.',
    preco: 179.0,
    estoque: 35,
    sku: 'AC-TP-120',
    categoriaRef: 'conforto',
    compat: [],
  },
  {
    slug: 'capa-banco-couro-sintetico',
    nome: 'Capas de Banco em Couro Sintético',
    descricao: 'Jogo completo, costura reforçada, compatível com airbag lateral.',
    preco: 459.0,
    estoque: 9,
    sku: 'AC-CB-121',
    categoriaRef: 'conforto',
    compat: [],
  },
  {
    slug: 'engate-reboque',
    nome: 'Engate de Reboque Removível',
    descricao: 'Engate com bola removível, capacidade 750 kg. Homologado.',
    preco: 690.0,
    estoque: 7,
    sku: 'AC-ER-122',
    categoriaRef: 'conforto',
    compat: ['volkswagen-gol', 'fiat-palio'],
  },
  {
    slug: 'jogo-calotas-aro-14',
    nome: 'Jogo de Calotas Aro 14',
    descricao: 'Quatro calotas em ABS de alto impacto, encaixe universal.',
    preco: 219.9,
    estoque: 26,
    sku: 'AC-CL-130',
    categoriaRef: 'rodas-pneus',
    compat: ['chevrolet-celta', 'fiat-palio', 'volkswagen-gol'],
  },
];

module.exports = { categorias, pecas, acessorios };
