// Dados de veículos para o seed.
// `modeloRef` liga cada carro a um ModeloVeiculo (usado para peças compatíveis).
// Imagens ficam em frontend/public/carros/ (baixadas da OLX, que bloqueia hotlink).

const modelos = [
  { slug: 'chevrolet-celta', marca: 'Chevrolet', modelo: 'Celta' },
  { slug: 'chevrolet-opala', marca: 'Chevrolet', modelo: 'Opala' },
  { slug: 'fiat-palio', marca: 'Fiat', modelo: 'Palio' },
  { slug: 'volkswagen-fusca', marca: 'Volkswagen', modelo: 'Fusca' },
  { slug: 'volkswagen-gol', marca: 'Volkswagen', modelo: 'Gol' },
  { slug: 'toyota-corolla', marca: 'Toyota', modelo: 'Corolla' },
];

// Gera os caminhos das imagens locais de um carro: /carros/<slug>-0.jpg ...
const imgs = (slug, n) => Array.from({ length: n }, (_, i) => `/carros/${slug}-${i}.jpg`);

const carros = [
  {
    slug: 'celta',
    nome: 'Chevrolet Celta LT 2015',
    marca: 'Chevrolet',
    modeloRef: 'chevrolet-celta',
    modelo: 'Celta LT 1.0',
    ano: 2015,
    preco: 33000,
    quilometragem: '114.000 km',
    cor: 'Prata',
    combustivel: 'Flex',
    portas: 4,
    cambio: 'Manual',
    carroceria: 'Hatch',
    finalPlaca: 5,
    localizacao: 'Sinop - MT',
    imagens: imgs('celta', 5),
  },
  {
    slug: 'palio',
    nome: 'Fiat Palio Way 2016',
    marca: 'Fiat',
    modeloRef: 'fiat-palio',
    modelo: 'Palio Way 1.0',
    ano: 2016,
    preco: 36000,
    quilometragem: '89.000 km',
    cor: 'Prata',
    combustivel: 'Flex',
    portas: 4,
    cambio: 'Manual',
    carroceria: 'Hatch',
    finalPlaca: 3,
    localizacao: 'Sinop - MT',
    imagens: imgs('palio', 1),
  },
  {
    slug: 'opala',
    nome: 'Chevrolet Opala Comodoro 1986',
    marca: 'Chevrolet',
    modeloRef: 'chevrolet-opala',
    modelo: 'Opala Comodoro Coupé',
    ano: 1986,
    preco: 45000,
    quilometragem: '65.300 km',
    cor: 'Prata',
    combustivel: 'Álcool',
    portas: 2,
    cambio: 'Manual',
    carroceria: 'Coupé',
    finalPlaca: 7,
    localizacao: 'Sinop - MT',
    imagens: imgs('opala', 5),
  },
  {
    slug: 'fusca',
    nome: 'Volkswagen Fusca 1972',
    marca: 'Volkswagen',
    modeloRef: 'volkswagen-fusca',
    modelo: 'Fusca 1300',
    ano: 1972,
    preco: 25000,
    quilometragem: '78.000 km',
    cor: 'Bege',
    combustivel: 'Gasolina',
    portas: 2,
    cambio: 'Manual',
    carroceria: 'Sedan',
    finalPlaca: 4,
    localizacao: 'Sinop - MT',
    imagens: imgs('fusca', 1),
  },
  {
    slug: 'corolla',
    nome: 'Toyota Corolla GRS 2022',
    marca: 'Toyota',
    modeloRef: 'toyota-corolla',
    modelo: 'Corolla GRS 2.0',
    ano: 2022,
    preco: 140000,
    quilometragem: '3.500 km',
    cor: 'Branco',
    combustivel: 'Flex',
    portas: 4,
    cambio: 'Automático',
    carroceria: 'Sedan',
    finalPlaca: 2,
    localizacao: 'Sinop - MT',
    imagens: imgs('corolla', 4),
  },
  {
    slug: 'gol',
    nome: 'Volkswagen Gol 2020',
    marca: 'Volkswagen',
    modeloRef: 'volkswagen-gol',
    modelo: 'Gol 1.0',
    ano: 2020,
    preco: 40000,
    quilometragem: '52.000 km',
    cor: 'Branco',
    combustivel: 'Flex',
    portas: 4,
    cambio: 'Manual',
    carroceria: 'Hatch',
    finalPlaca: 1,
    localizacao: 'Sinop - MT',
    imagens: imgs('gol', 1),
  },
];

module.exports = { modelos, carros };
